### ISSUE TITLE
Modificar las tablas para abarcar nuevos tipos de documentos

### ISSUE THREAD

**Issue by mem0rias** [mem0rias/KiaraDev#20]
El nuevo modelo de datos utilizado para los expedientes simplifica que los archivos se compartan entre expedientes, pero tenemos que especificar otros mas por esto. Una alternativa es duplicar archivos entre expedientes, o generar nuevos tipos,eg. (Identificacion conyuge, Id solidario para arrendar, etc...)

**Comment by DanCordova** [comment]
Ya quedó gracias
